language: java
jdk:
  - oraclejdk7

install:
    - TERM=dumb ./gradlew assemble

script:
    - TERM=dumb ./gradlew check

after_failure: 
    - echo "HOLA"
    - echo %TRAVIS_TEST_RESULT%
    - ./print_errors.sh

