language: java
jdk:
  - oraclejdk7

install:
    - # disabled temporarly TERM=dumb ./gradlew assemble

script:
    - # disabled temporarly TERM=dumb ./gradlew assemble

after_failure: 
    - ls -la build/reports/tests
    - chmod +x ./print_errors.sh
    - ./print_errors.sh

